#!/bin/sh

. /usr/share/java-utils/java-functions

if [ "$APPDIR" == "" ]; then
    APPDIR=/usr/share/arduino
fi

MAIN_CLASS=processing.app.Base

set_classpath ecj jna RXTXcomm
for lib in "$APPDIR"/{,lib}/*.jar; do
    CLASSPATH="$CLASSPATH:$lib"
done

set_flags -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel

arduino_dirs="hardware/arduino/avr hardware/arduino/sam hardware/tools lib reference tools"
atexit()
{
    local rc=$?
    for dir in $arduino_dirs; do
        test -e $dir -a -L $dir && rm -f $dir
    done
    exit $rc
}

trap atexit EXIT TERM
for dir in $arduino_dirs; do
    if [ ! -e $dir -o -L $dir ]; then
        parent_dir="$(dirname $dir)"
        source_path="$APPDIR/$dir"
        test "$parent_dir" == "" -o "$parent_dir" == "." ||
            source_path="$(echo "$parent_dir" | sed -e 's|[^/]*|..|g')/$source_path"
        ln -fs "$source_path" "$parent_dir"
    fi
done

(run "$@")
