#!/bin/sh

. /usr/share/java-utils/java-functions

MAIN_CLASS=processing.app.Base

set_classpath ecj jna RXTXcomm
for lib in /usr/share/arduino/*.jar; do
    CLASSPATH="$CLASSPATH:$lib"
done

set_flags -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel

cd /usr/share/arduino
run "$@"
